// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abbgxbsbisuvczeulvhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiYmd4YnNiaXN1dmN6ZXVsdmhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTEzNzgsImV4cCI6MjA3MzU4NzM3OH0.Sp44PyR1B-pT9lAnTJx9yewk4tbA6PeTTOnc9kuaxXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});